### PR TITLE
Adding operation in table details page

### PR DESCRIPTION
**Pull request by shahsank3t**
## Description
Added Table Operations:
image

Support to switch Table Schema from table view to JSON view and vice-versa:
image

Showing Instance name and # of the segment in table details page:
image

Reload Status Modal:
image

Rebalance Server Modal:
image

Rebalance Server Modal Response:
image

### CODE REVIEW

**Comment by npawar** [comment]
@shahsank3t Where are you getting the state for enable/disable table? Are you reading the ideal state znode?

**Comment by npawar** [comment]
When I deleted the table, I got a blank screen. I think it happened because I edited the server config, and changed DefaultTenant to something else. If a tenant has only broker or server and not both, it seems to be crashing.
Screen Shot 2020-10-28 at 1 34 54 PM

**Comment by shahsank3t** [comment]
@npawar 
>@shahsank3t Where are you getting the state for enable/disable table? Are you reading the ideal state znode?

Currently, I am not getting the state from anywhere but rather always defaulting it to enabled and post that maintain the state locally. I'll try to get from the znode state.

>When I deleted the table, I got a blank screen. I think it happened because I edited the server config, and changed DefaultTenant to something else. If a tenant has only broker or server and not both, it seems to be crashing.

Can you share the steps to change the tenant's name? I'd like to reproduce and fix it accordingly.

**Comment by npawar** [comment]
> @npawar
> 
> > @shahsank3t Where are you getting the state for enable/disable table? Are you reading the ideal state znode?
> 
> Currently, I am not getting the state from anywhere but rather always defaulting it to enabled and post that maintain the state locally. I'll try to get from the znode state.

Regarding the enable/disable, the problem right now is that if I disable a table and then go to a different page, the state is forgotten. I would suggest just greying out that operation for now.  @galalen is working on adding an API to get the state https://github.com/apache/incubator-pinot/issues/6169

> 
> > When I deleted the table, I got a blank screen. I think it happened because I edited the server config, and changed DefaultTenant to something else. If a tenant has only broker or server and not both, it seems to be crashing.
> 
> Can you share the steps to change the tenant's name? I'd like to reproduce and fix it accordingly.


For the blank screen, here were my steps:
1. Started OfflineQuickStart
2. Go to Tenants -> DefaultTenant -> Broker instance.
3. Click on Edit Tags. 
4. Removed DefaultTenant_OFFLINE, added neha_OFFLINE.
5. Came back to Home. 
6. Clicked on Tenants -> DefaultTenant (or neha tenant). Got blank screen

**Comment by npawar** [comment]
Another issue:
I went to Broker instance, removed DefaultTenant and added neha_BROKER
I went to Server instance, removed DefaultTenant and added neha_OFFINE
Now I wanted to go to my Table and edit the table config, but I cannot see that table. I'm guessing the call to fetch the tenant is failing, coz the table still refers to DefaultTenant. 

We should still show the Table in the list.

**Comment by shahsank3t** [comment]
@npawar - addressed & fixed all the changes you mentioned.

**Review by npawar — APPROVED** [review]
Verified that all changes are working correctly.

**Pull request merged**
