### PR TITLE
Add columnTotalLength into column metadata for String column.

### PR DESCRIPTION
**Pull request by mqliang**
## Description

This PR:
* change the server API `@Path("/tables/{tableName}/segments/{segmentName}/metadata")` return all columns's metadata by default (if user does not provide custom column filter).
* for String/Byte column, add  columnTotalLength into column metadata. For columns of other type (INT/LONG, etc), the value of columnTotalLength is always -1;
* columnTotalLength only works for offline table, for realtime table, the value is always -1;

Attached the response of `curl http://localhost:9000/segments/baseballStats/metadata` to showcase the change. The baseballStats table is created by `bin/quick-start-batch.sh`

[baseballStats_metadata.txt](https://github.com/apache/incubator-pinot/files/6646087/baseballStats_metadata.txt)

cc @siddharthteotia 

## Upgrade Notes
Does this PR prevent a zero down-time upgrade? (Assume upgrade order: Controller, Broker, Server, Minion)
* [ ] Yes (Please label as **<code>backward-incompat</code>**, and complete the section below on Release Notes)

Does this PR fix a zero-downtime upgrade introduced earlier?
* [ ] Yes (Please label this as **<code>backward-incompat</code>**, and complete the section below on Release Notes)

Does this PR otherwise need attention when creating release notes? Things to consider:
- New configuration options
- Deprecation of configurations
- Signature changes to public methods/interfaces
- New plugins added or old plugins removed
* [ ] Yes (Please label this PR as **<code>release-notes</code>** and complete the section on Release Notes)

### CODE REVIEW

**Comment by mqliang** [comment]
@siddharthteotia The reason to change the server API @Path("/tables/{tableName}/segments/{segmentName}/metadata") return ALL columns's metadata by default: intuitively, the overhead of querying this API is not CPU/MEM (all column's metadata is aways calculated at server, we just not send all of them back to client if user provide a column filter). My understanding is the overhead is mainly at networking side. For networking, the main cost is establishing connection, networking packet get queued/buffered in router, retransmission during networking jitter, etc. Unless the user only need query few columns while the table has hundreds/thousands of columns, the overhead of sending extra columns metadata is minimal.

Let me know if you have any concerns, I can change it as: return NO columns's metadata by default if user does not provide any filter.

**Comment by mqliang** [comment]
@siddharthteotia BTW, the PR change the metadata layout, so will bring incompatibility. Let's discuss that.

**Comment by mayankshriv** [comment]
> @siddharthteotia BTW, the PR change the metadata file layout, so will bring incompatibility. Let's discuss that.

Hmm, this is a read-only api, right? If so, what's the need for incompatible change? Please lets avoid that unless it is warrented.

**Comment by mayankshriv** [comment]
I also recommend the following:
1. We should add other info like the index/dictionary size.
2. Any zk metadata (seems as though you may have already added it).
3. Let's put a bit more thought to the rest apis. For example, I can see it would be useful to have
   - column level
   - segment level
   - server level
   - table level (size of a column index across the table)
   - Individual metadata (eg size, dictionary size cardinality etc), returning giant blog everytime is not a good idea, so we should have a hierarchical path that allows to zoom in/out. (This can be an enhancement, but we should layout the api hierarchy from the start).

**Comment by siddharthteotia** [comment]
> > @siddharthteotia BTW, the PR change the metadata file layout, so will bring incompatibility. Let's discuss that.
> 
> Hmm, this is a read-only api, right? If so, what's the need for incompatible change? Please lets avoid that unless it is warrented.

Yes we don't need that change. Will discuss once with @mqliang  and then change it accordingly.

**Comment by mqliang** [comment]
close this in favor of: https://github.com/apache/incubator-pinot/pull/7061

**Pull request closed without merging**
