### PR TITLE
[TE] Add data set display name and show it on UI

### PR DESCRIPTION
**Pull request by jihaozh**
- Add the ability to set dataset's display name. If the display name is set, the UI will show the display name instead of the dataset key.
- Add dataset and granularity filters in the alert list page.

### CODE REVIEW

**Comment by akshayrai** [comment]
@jihaozh can you provide some context (example might help) behind why we need the display name?

**Comment by harleyjj** [comment]
It looks good, but it's failing CI tests

**Comment by jihaozh** [comment]
> @jihaozh can you provide some context (example might help) behind why we need the display name?

Added this per the requirements of UMP alert onboarding. I'll send a follow-up RB to fill the display name for UMP datasets.

**Comment by jihaozh** [comment]
> It looks good, but it's failing CI tests

Thanks. Just pushed the fix for the front end tests.

**Pull request merged**
