### PR TITLE
#4317 Feature/variable length bytes offline dictionary

### PR DESCRIPTION
**Pull request by buchireddy**
PR for the feature mentioned in #4317

### CODE REVIEW

**Comment by snleee** [comment]
@buchireddy Can you rebase the code from `apache/incubator-pinot` master branch? Also, it seems that your pr includes some other commits from `winedepot` branch. If would be great if you can cherry pick the branch so that this pr only includes the code changes related to variable length byte & string support for dictionary.

**Comment by buchireddy** [comment]
@snleee Closing this PR since I don't want to merge all other changes from winedepot fork. I've open https://github.com/apache/incubator-pinot/pull/4321 with the intended changes only.

**Comment by mcvsubbu** [comment]
@buchireddy  did you consider the use of [MutableOffheapByteArrayStore](https://github.com/apache/incubator-pinot/blob/master/pinot-core/src/main/java/org/apache/pinot/core/io/writer/impl/MutableOffHeapByteArrayStore.java)? I am not able to readily say whether your implementation is based on that or is something parallel.

**Comment by buchireddy** [comment]
@mcvsubbu I did look at `MutableOffheapByteArrayStore` and took some concepts from it while implementing `VarLengthBytesValueReaderWriter` too. However, I haven't used the former fully because of the following reasons:
* In order to support a seamless transition from fixed length to variable length offline dictionary, we need a special magic header to be added at the beginning, which needs some changes to  `MutableOffheapByteArrayStore`.
* `MutableOffheapByteArrayStore` is handling the buffer expansions, multiple buffers logic because it needs to be mutable but the immutable one doesn't need all those.

So, it's a trade-off b/w simple code vs avoiding the code duplication (though we anyways need a new class for variable length dictionary class implementation). I'm open for debate and for further brainstorming.

P.S: This is my first time going through Pinot code so please let me know if I'm missing any aspects here.

**Comment by mcvsubbu** [comment]
Mutable byte array store can be modified to have a header, no problem. It is currently used as a volatile store for comsuming segments, so changing it to include a header is not backward incompatible.

Why not modify it to have the header and also derive an unmutable class from it to be used during segment generation?

**Comment by kishoreg** [comment]
Let’s move the discussion to the issue #4317.

**Pull request closed without merging**
