### PR TITLE
6355 don't lose authority portion of inputDirURI

### PR DESCRIPTION
**Pull request by kkrugler**
## Description
Fix for issue #6355.

Support for `inputDirURI` in job file that uses authority (HDFS namenode, for example).

Tried it out with my use case and it fixed the problem I encountered, as per #6355.

I had done a complete build (including top-level `mvn eclipse:eclipse`) prior to this patch, and wound up with two artifacts (`.externalToolBuilders/` and `maven-eclipse.xml`) that were being treated as new files, so I excluded them via a change to `.gitignore`, don't know if that should have a separate PR.

Also the `Pinot Batch Ingestion Standalone` sub-project didn't have any unit tests previously, not sure if I configured things properly (I use `JUnit 4` not `testng`), so looking for input, thanks!

### CODE REVIEW

**Comment by fx19880617** [comment]
Thanks! 
Can you also add a test for `SegmentGenerationUtils.getRelativeOutputPath(...)` with the example you have. So we can ensure this works for your use case.

**Comment by kkrugler** [comment]
Hi @fx19880617 - OK, test added.

**Comment by kkrugler** [comment]
Hi @fx19880617 - I looked at the failing unit test report. It seems to be in a test that I didn't change (`testNonMatchingRequestId(org.apache.pinot.core.transport.QueryRoutingTest`) plus other tests in `QueryRoutingTest`. Do these sometimes randomly fail? Or should I dig deeper?

**Comment by fx19880617** [comment]
> Hi @fx19880617 - I looked at the failing unit test report. It seems to be in a test that I didn't change (`testNonMatchingRequestId(org.apache.pinot.core.transport.QueryRoutingTest`) plus other tests in `QueryRoutingTest`. Do these sometimes randomly fail? Or should I dig deeper?

I don't think it's relevant. Let me dig more.

**Review by fx19880617 — APPROVED** [review]

**Comment by fx19880617** [comment]
Thanks for fixing this!

**Pull request merged**
