### PR TITLE
[TE] Remove maven-shade-plugin and switch from org.reflections to io.classgraph

### PR DESCRIPTION
**Pull request by vincentchenjl**
This PR is achieve following items:

- Remove `maven-shade-plugin` from `thirdeye-dashboard` module
- Switch  from `org.reflections` to `io.classgraph` to reflect detection and alert components in `DetectionRegistry` and  `DetectionAlertRegistry`
- Remove `ch.qos.logback` from exclusion in the `pom.xml` of `thirdeye-dashboard`

### CODE REVIEW

**Review by suvodeep-pyne — APPROVED** [review]
@vincentchenjl This looks great! I was looking for a fix for this. Thanks a lot! LGTM

Quick Question: Does this new library work with higher versions of Java. org.reflections had issues with Java 9 ad above.

**Comment by vincentchenjl** [comment]
> Quick Question: Does this new library work with higher versions of Java. org.reflections had issues with Java 9 ad above.
Yes, the new library works with Java 9 based on their wiki.
https://github.com/classgraph/classgraph/wiki#use-as-a-module

**Review by jihaozh — APPROVED** [review]
Awesome. LGTM

**Comment by jenya** [comment]
@vincentchenjl is it expected that removing maven-shade-plugin broke all run scripts (run-frontend.sh, run-backend.sh and docker)?
Build doesn't produce fat jar in `./target/thirdeye-dashboard-1.0.0-SNAPSHOT.jar`. This jar is used by all run scripts.

**Pull request merged**
