### PR TITLE
[TE] Remove datepartition for presto queries to unblock other usecases

### PR DESCRIPTION
**Pull request by akshayrai**

### CODE REVIEW

**Comment by ilyanoskov** [comment]
Hey everyone, this does not work
```
ERROR [2019-11-08 09:27:58,691] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: 6f3bf35155fbbaca
! com.facebook.presto.jdbc.internal.client.FailureInfo$FailureException: Invalid format: "2019-10-28 12:35:46.948" is malformed at "48"
! at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:945)
! at com.facebook.presto.operator.scalar.DateTimeFunctions.parseDateTimeHelper(DateTimeFunctions.java:575)
! ... 16 common frames omitted
! Causing: com.facebook.presto.jdbc.internal.client.FailureInfo$FailureException: Invalid format: "2019-10-28 12:35:46.948" is malformed at "48"
! at com.facebook.presto.operator.scalar.DateTimeFunctions.parseDateTimeHelper(DateTimeFunctions.java:578)
! at com.facebook.presto.operator.scalar.DateTimeFunctions.parseDatetime(DateTimeFunctions.java:560)
! at com.facebook.presto.$gen.CursorProcessor_20191108_092758_125.filter(Unknown Source)
! at com.facebook.presto.$gen.CursorProcessor_20191108_092758_125.process(Unknown Source)
! at com.facebook.presto.operator.ScanFilterAndProjectOperator.processColumnSource(ScanFilterAndProjectOperator.java:239)
! at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:231)
! at com.facebook.presto.operator.Driver.processInternal(Driver.java:379)
! at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)
! at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)
! at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
! at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1065)
! at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
! at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)
! at com.facebook.presto.$gen.Presto_0_215____20191021_124416_1.run(Unknown Source)
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
! at java.lang.Thread.run(Thread.java:748)
```

**Comment by kishoreg** [comment]
how is the date column stored in MySQL. Can you provide sample column value

**Comment by ilyanoskov** [comment]
``` Invalid format: "2019-11-09 20:50:21.464" is malformed at "64"```

this is the error I get in which you can see the sample column value

**Comment by ilyanoskov** [comment]
@xiaohui-sun @akshayrai

**Pull request merged**
