### PR TITLE
Support for Update & Delete in ZooKeeper Browser and added SQL Functions in SQL Editor autocomplete list

### PR DESCRIPTION
**Pull request by shahsank3t**
## Description
Added support for Update & Delete in Zookeeper Browser.
image

image

Added SQL Functions in SQL Editor's autocomplete list.
image

### CODE REVIEW

**Comment by kishoreg** [comment]
Tested it and it works fine. Few things
- Ask for confirmation before saving instead of before editing
- Refresh seems to refresh the entire tree, just refresh the path that is selected
- display the refresh time on the top (maintain this for each node)

**Comment by shahsank3t** [comment]
@kishoreg Addressed your feedback and also added Success & Error Notification Alerts on completion of Update/Delete Operation.

**Review by kishoreg — APPROVED** [review]
Please rebase

**Comment by shahsank3t** [comment]
@kishoreg rebased and all checks passed.

**Review by kishoreg — APPROVED** [review]

**Pull request merged**
