### PR TITLE
Enhance AggregationFunctionColumnPair to accept underscore in function name

### PR DESCRIPTION
**Pull request by Jackie-Jiang**

### CODE REVIEW

**Comment by pradeepgv42** [comment]
Looks good to me, thanks

**Review by fx19880617 — APPROVED** [review]

**Comment by fx19880617** [comment]
I think we are still missing this support for transform functions

**Comment by Jackie-Jiang** [comment]
> I think we are still missing this support for transform functions

You mean pre-aggregation on transformed columns?

**Comment by fx19880617** [comment]
> > I think we are still missing this support for transform functions
> 
> You mean pre-aggregation on transformed columns?

I mean transform functions like `array_sum` is not supported yet only `arraysum`

**Comment by Jackie-Jiang** [comment]
The function in star-tree can only be aggregation function (pre-aggregation)

**Comment by fx19880617** [comment]
oh i'm justing talking about for regular transform functions usage:
```
select array_sum(mvCol) from myTable
```

**Comment by Jackie-Jiang** [comment]
> oh i'm justing talking about for regular transform functions usage:
> 
> ```
> select array_sum(mvCol) from myTable
> ```

It's handled within `TransformFunctionType.getTransformFunctionType()`

**Pull request merged**
