### PR TITLE
Making pushType non-mandatory

### PR DESCRIPTION
**Pull request by icefury71**
## Description
As part of #5942 pushType was made mandatory for offline tables my mistake. Removing this mandate. 

## Upgrade Notes
Does this PR prevent a zero down-time upgrade?
No

Does this PR fix a zero-downtime upgrade introduced earlier?
No

Does this PR otherwise need attention when creating release notes?
No

### CODE REVIEW

**Comment by npawar** [comment]
Along with this, I think we also need to make APPEND the default? I remember there were some retention related issues.
From retention manager
```
String segmentPushType = validationConfig.getSegmentPushType();
    if (tableConfig.getTableType() == TableType.OFFLINE && !"APPEND".equalsIgnoreCase(segmentPushType)) {
      LOGGER.info("Segment push type is not APPEND for table: {}, skip", tableNameWithType);
      return;
    }
```

**Review by npawar — APPROVED** [review]

**Review by mcvsubbu — CHANGES_REQUESTED** [review]
It the push type is not there on the append table, we will have trouble naming segments correctly

**Comment by jackjlli** [comment]
The config `segmentPushType` is needed at least in the following scenarios:
1. Retention manager needs it to purge segments: https://github.com/apache/incubator-pinot/blob/9929dad2e804f525b8ace925e859e07c6fdee9da/pinot-controller/src/main/java/org/apache/pinot/controller/helix/core/retention/RetentionManager.java#L104
2. `TableRetentionValidator` gets called https://github.com/apache/incubator-pinot/blob/fb043dab7d5fef3ef726896d2f53e45a2fd69f22/pinot-controller/src/main/java/org/apache/pinot/controller/util/TableRetentionValidator.java#L112
3. Segment creation Hadoop/Spark job requires it to validate the time column: https://github.com/apache/incubator-pinot/blob/fb043dab7d5fef3ef726896d2f53e45a2fd69f22/pinot-plugins/pinot-batch-ingestion/v0_deprecated/pinot-hadoop/src/main/java/org/apache/pinot/hadoop/job/HadoopSegmentCreationJob.java#L145
4. Segment creation job requires it to generate the segment name: https://github.com/apache/incubator-pinot/blob/540853d786c9e4b4bb27bf4bbc6fa73837ff1bc3/pinot-core/src/main/java/org/apache/pinot/core/segment/name/NormalizedDateSegmentNameGenerator.java#L48

So if you remove the check, you'd also need to adjust those logic to avoid breaking the current behaviors.

**Comment by snleee** [comment]
If we want to remove the mandatory check, we should adjust codes to align all the usage with falling back to the default behavior. We can make `APPEND` as the default behavior since it's the most common use case. Currently, the code explicitly checks the `APPEND` in most cases, so `null` value for push type will end up with the `REFRESH` behavior.

**Comment by Jackie-Jiang** [comment]
@mcvsubbu @jackjlli @snleee The mandatory check is just introduced in #6073, and might break the existing use cases without the push type configured (correct me if I was wrong @icefury71 ). I think there are offline use cases within LinkedIn without the push type, which will break.
We cannot directly change the default behavior to use `APPEND` if the push type is not mandatory for the existing use cases.

**Comment by icefury71** [comment]
> @mcvsubbu @jackjlli @snleee The mandatory check is just introduced in #6073, and might break the existing use cases without the push type configured (correct me if I was wrong @icefury71 ). I think there are offline use cases within LinkedIn without the push type, which will break.
> We cannot directly change the default behavior to use `APPEND` if the push type is not mandatory for the existing use cases.

Yes, this was mostly to conserve the existing use cases that don't explicitly specify a push type. Hence I removed the mandate.

However, I did choose to add a default value (APPEND) since it will break the retention manager otherwise. @Jackie-Jiang lemme know if there are any implications of this assumption ? As @mcvsubbu mentioned, most of the code places kinda assume APPEND semantics.

**Comment by mcvsubbu** [comment]
ah ok, I was thinking push-frequency

**Review by mcvsubbu — APPROVED** [review]

**Comment by jackjlli** [comment]
@icefury71 The 4th item I pasted above is the one we should be cautious about:
https://github.com/apache/incubator-pinot/blob/540853d786c9e4b4bb27bf4bbc6fa73837ff1bc3/pinot-core/src/main/java/org/apache/pinot/core/segment/name/NormalizedDateSegmentNameGenerator.java#L53

The boolean value depends on whether the push type is shown as `APPEND` in the table config. If it's missing or it's REFRESH, (or it's mis-spelled), the behavior will be different. In this case, the missing pushType behavior is the same as `REFRESH` push type, which violates your default assumption.

**Comment by icefury71** [comment]
Removed the default value based on this conversation. We're now back to the old behaviour where push type is not mandatory and no default value assigned.

**Review by Jackie-Jiang — APPROVED** [review]
LGTM

**Pull request merged**
