### PR TITLE
Refactor pinot record reader dependency

### PR DESCRIPTION
**Pull request by fx19880617**
1. Refactor to make `pinot-orc` only depends on `pinot-spi`
2. Refactor to make `pinot-parquet` only depends on `pinot-spi`
3. Refactor to move `RecordReaderUtils` from `org.apache.pinot.core.data.readers.RecordReaderUtils` to `org.apache.pinot.spi.data.readers.RecordReaderUtils`
4. Adding `pinot-avro` module and move `org.apache.pinot.core.data.readers.AvroRecordReader` to it.
5. Refactor `{Avro/Parquet/Csv/Json}RecordReaderTest` to extend `org.apache.pinot.spi.data.readers.AbstractRecordReaderTest`.

### CODE REVIEW

**Comment by kishoreg** [comment]
Looks good. Nothing to do with this PR but we should clean up RecordReaderUtils. Looks like it has some methods related to IOUtils and DataType utils.

**Comment by kishoreg** [comment]
Nice job extracting AbstractRecordReaderTest. We can make it better in the next iteration.

**Comment by kishoreg** [comment]
Also, once we have the ability to dynamically load record-reader impls, we can remove pinot-avro dependency from pinot-core right?

**Comment by fx19880617** [comment]
> Also, once we have the ability to dynamically load record-reader impls, we can remove pinot-avro dependency from pinot-core right?

Not really, RecordReader part is ok, but there is also many dependencies on `org.apache.pinot.avro.data.readers.AvroUtils`

**Pull request merged**
