### PR TITLE
Changing the rebalance strategy from Crush to AutoRebalance for contr…

### PR DESCRIPTION
**Pull request by kishoreg**
…oller

@jackjlli Can you please review this? This removes the exception we are seeing. I don't see any reason to use CrushAlgorithm. It's for advanced use cases and we don't need it for Controller.
Also, why should we model it as MasterSlave instead of using a simple online/offline model? I dint bother changing the state model since it requires changes elsewhere.

Please review this

### CODE REVIEW

**Comment by jackjlli** [comment]
@kishoreg Thanks for inviting. While this algorithm is needed to provide even distribution and minimum partition movements instances go up/down. The AutoRebalance algorithm isn't deterministic, which doesn't guarantee the previous controller will become the one for the same partitions after restarting the host.
For MasterSlave state model, this is also needed as well, because we want to make sure there is at most 1 host being the master within the partition. OnlineOffline state model doesn't guarantee that; it's possible there are more than one host in online state within a short period of time, which is especially harmful for realtime segment completion.
I think the best approach to remove that alert/exception is to contact Helix team to unify the behaviors of all the algorithms.

**Comment by kishoreg** [comment]
Controller are not state full systems. We don’t need affinity when controller start/stop. Why do you say that there will more than one host in online state?

**Comment by mcvsubbu** [comment]
We expect to move to 0.9.2 in the next few weeks, if that helps.

**Comment by kishoreg** [comment]
> We expect to move to 0.9.2 in the next few weeks, if that helps.

It won't help. that code still throws that exception. I am not sure why we need such a complex rebalancing strategy - distributing tables among controllers is a fairly simple problem that can be solved with online-offline state model. See this recipe https://helix.apache.org/0.6.4-docs/recipes/lock_manager.html

**Comment by jackjlli** [comment]
Affinity is needed when controller's workload is distributed to multiple controllers. 
E.g. suppose the leader of Partition X is host_1. After restarting host_1, we don't want the leader of partition X gets changed to other controller hosts after host_1 has been fully restarted; we want host_1 to always be the leader of Partition X. This can reduce the change of leadership change in the whole Pinot cluster. And crushED algorithm provides us this guarantee:
http://helix.apache.org/0.8.4-docs/design_crushed.html

0.9.2 will also touch that exception, but it only prints a one-line message instead of the whole stack trace. Thus, the log will be clean. And the message will not longer appear after the first controller is fully prepared.

The goal of leadControllerResource is to make sure there is at most 1 host in Master state within any partitions. OnlineOffline cannot guarantee that. E.g. if OnlineOffline state model is used, when a host gets restarted, it's possible that a state transition from offline to online gets triggered before the state transition from online to offline does, which leads to a scenario that there are two hosts in Online state, which is harmful to realtime segment completion.

**Comment by kishoreg** [comment]
Why do we need that behavior? I can understand that behavior for a Sharded database, but there is no need for the same controller to be manage a table in case of Pinot controller.

**Comment by kishoreg** [comment]
The information about online offline model is incorrect. Helix sends online to offline first to current leader before sending offline to online to another node.

**Comment by jackjlli** [comment]
That behavior is quite useful especially when some issue needs to be debugged; we don't want the logging info of a table spreads across all the controllers.

As for OnlineOffline state model, it won't restrict the online replica to be 1. This info is confirmed by Helix team and they recommend using MasterSlave/LeadStandby instead of OnlineOffline model.

**Comment by kishoreg** [comment]
why will debug logs be spread across multiple logs if there is no failure. And if there is a failure, it will be in different logs in both cases. 

Can you start a thread on Helix mailing list. I would like to understand why online offline model won’t work.

**Comment by kishoreg** [comment]
Thanks @jackjlli. You can always change the rebalancer at runtime and it should work. 

https://github.com/apache/helix/issues/680

**Pull request merged**
