### PR TITLE
Added proper tooltips, ability to enable-disable table state and fixed page crash on reload status

### PR DESCRIPTION
**Pull request by shahsank3t**
## Description
Ability to enable/disable table state:
image

Tooltip Example:
image

### CODE REVIEW

**Comment by npawar** [comment]
Thanks @shahsank3t ! Few missing tooltips and comments:

1. Add tooltip for Estimated size to individual table page
2. Add tooltip for Reported size, estimated size, status to the Tables page
3. Transform functions link broken on Add Offline page
4. Link for Indexing and Encoding missing
5. For some links (noticed in Filter and transform function, and all links on REALTIME table page as well), it is opening in same page instead of new tab. Can we make it always open in new tab?
6. Relocate to tag tooltip missing
7. StreamConfigs tooltip appears far away and disappears when trying to click
8. Repeat all tooltips from the OFFLINE table to the REALTIME table form
9. The “i”  in the purple circle UI for the links was not very intuitive for me. I kept expecting some info to pop up. Any other way to show it? The “click here for details” you’ve added to some tooltips is great.

**Comment by shahsank3t** [comment]
@npawar added all the missing tooltip and addressed other review comments.

**Review by npawar — APPROVED** [review]
LGTM.
Just one minor comment - the tooltip on “Stream Configs” has a link to transform functions. Remove the link, no need of any link there

**Comment by shahsank3t** [comment]
@npawar - Removed the link and updated the PR.

**Pull request merged**
