### PR TITLE
Refactor Predicate classes and make them easier to use

### PR DESCRIPTION
**Pull request by Jackie-Jiang**
- Change Predicate to an interface
- Add PredicateFactory to construct predicates

### CODE REVIEW

**Comment by siddharthteotia** [comment]
It looks like this PR was built on top of the commit from the other open PR https://github.com/apache/incubator-pinot/pull/4924

Not sure if that was intentional

**Comment by Jackie-Jiang** [comment]
@siddharthteotia Yes, it is intentional, and noted in the pr description. Will get them merged in sequence

**Comment by mayankshriv** [comment]
Seems there may be multiple ways to clean up here. As discussed offline, could you also explore the idea of modeling Predicate as (LHS OP RHS) and make it part of FilterQueryTree, which the predicate evaluator can directly use?

**Comment by Jackie-Jiang** [comment]
> Seems there may be multiple ways to clean up here. As discussed offline, could you also explore the idea of modeling Predicate as (LHS OP RHS) and make it part of FilterQueryTree, which the predicate evaluator can directly use?

Predicate currently serves as an intermediate type to link the FilterQueryTree and the PredicateEvaluator. Because we want to move away from FilterQueryTree for SQL, it would be better to keep it separate, and use it as the intermediate type for the new filter tree

**Comment by Jackie-Jiang** [comment]
No longer needed after introducing the new Predicate classes in QueryContext (#5483)

**Pull request closed without merging**
