### PR TITLE
adding zookeeper browser module in UI

### PR DESCRIPTION
**Pull request by shahsank3t**
## Description
This PR is to add the Zookeeper Browser module into existing UI.
image
image

Added `Refresh` action functuality.
Added a "Functionality Coming Soon" text on `Add`, `Edit`, `Delete` Options in ZK Browser.
image

A couple of additional changes:
1. Replace "Open Sans" font with "Source Sans Pro"
2. The backdrop on the loading sign was giving an experience of screen flicker, fixed it by showing the loader on the top right part of the screen.
image

### CODE REVIEW

**Comment by kishoreg** [comment]
This is awesome! Please use /stat call for node metadata

**Comment by shahsank3t** [comment]
@kishoreg 
Addressed the comment and updated the PR.
image

**Comment by fx19880617** [comment]
This is awesome!

Two features maybe useful:
1. Show decoded message for compressed metadata. (E.g. large idealStates is compressed)
2. Search support based on either znode name and node content

**Comment by yupeng9** [comment]
This is awesome!

+1 to the search/filter support on the creation/updated time, to show most recent state changes.

**Comment by kishoreg** [comment]
> This is awesome!
> 
> +1 to the search/filter support on the creation/updated time, to show most recent state changes.

@yupeng9, can you elaborate on this? are you talking about ZK explorer.

**Comment by yupeng9** [comment]
> > This is awesome!
> > +1 to the search/filter support on the creation/updated time, to show most recent state changes.
> 
> @yupeng9, can you elaborate on this? are you talking about ZK explorer.

Yes, I was referring to the ZK explorer with a filter on ctime or mtime to inspect the recent changes or changes in a given time window.

**Pull request merged**
