### PR TITLE
support to add offline and realtime tables, individually able to add schema and schema listing in UI

### PR DESCRIPTION
**Pull request by shahsank3t**
## Description
image

Add Schema:
image

Add Offline Table:
image
image

Add Realtime Table:
image
image

### CODE REVIEW

**Comment by npawar** [comment]
Thanks @shahsank3t , this looks great!

I’ve listed some of the things that didn’t work for me/ would be nice to change:

1. Can we hide Multi value dropdown for METRIC and DATETIME?
2. In Add Schema - for the mandatory fields, can we have some validation on UI itself? For example, if someone tries to save a Schema without entering a SchemaName or a field’s dataType, currently a call is made to the backend, which fails, and that message is shown back on the UI. Instead, can the UI itself flag it, just by highlighting the incomplete field (and a message, please enter all fields). I’ve seen this done commonly on UIs.
3. Can we have separate starter json template for OFFLINE and REALTIME? In OFFLINE, we don’t want to show the streamConfigs, aggregateMetrics, tagOverrideConfig, peerSegmentDownloadSchema, completionConfig. Similarly, in REALTIME we don’t want to show segmentPushType, segmentPushFrequency and instanceAssignmentConfigMap
4. If someone Enables partitioning, all the columns that show up should be marked mandatory.
5. Same as 4 for Enable Replica Groups
6. TransformConfig  did not get set in the IngestionConfig when I added transform functions . I think it is getting created inside filterConfig (instead of outside under ingestionConfig)
7. PartitioningConfig is not getting set. Seeing an error. The json looks incorrect . I’ve added some comments in the doc about it
8. ReplicaGroupConfig is also not getting set. Seeing an error. The json I had provided is incomplete. Added the extra part in the doc.
9. In case of 7 & 8, the error is spilling out of the screen.
10. In REALTIME table, there is an extra blob of “streamConfigs” at the end of the json.
11. In REALTIME table, the changes I made to the stream config properties did not get reflected in the json (e.g. topic name, broker url, or editing the flush threshold time, or removing/adding any property). It is all getting set in that extra blob, as reported in 10.
12. I couldn’t create a REALTIME table. I think it’s because of the properties "stream.kafka.decoder.prop.schema.registry.schema.name" and "stream.kafka.decoder.prop.schema.registry.rest.url". Please remove them from the list.
13. Mark some of the stream config properties as Mandatory. I’ve updated the doc for which ones.
14. In case of REALTIME, when someone enables the “Replica Group”, don’t add the instanceAssignmentConfigMap json. It’s creating an incorrect table config which does not get saved. Either remove it (preferable), or just put null.

**Comment by shahsank3t** [comment]
@npawar Update the PR with the fixes for the issues you reported.

**Comment by npawar** [comment]
Some more issues:

1. Can we have Delete Schema  and `Edit Schema` button on the individual schema page? Otherwise there’s no way to delete/edit a schema, unless a table is also created.
2. UI side Validations for required fields on Add Schema didn’t work. I still see call being made to backend when I tried to add schema without specifying name
3. The “*” on Number of instances per replica group field spilled onto new line for my screen. We can reduce that string to Instances per replica group , or increase size of that text area.
4. When enabling Partitioning, the “segmentPrunerTypes” did not get set in the routing config. Refer to the doc for how to set. Both for REALTIME & OFFLINE
5. When Enable Partitioning, mark all mandatory fields as red *. I see it only for OFFLINE, it’s missing for REALTIME
6. In stream configs, mark these properties as mandatory - topic.name, broker.list, consumer.type, decoder.class.name
7. Seeing spinning wheel forever in this scenario -

- Created a schema “foo” with 1 dimension.
- Add OFFLINE table, with name “foo”. When adding table, Enable Replica Groups, and add 2 replica groups and 2 instances per replica groups (this is expected to work only with 1,1 since we have only 1 server). So, the backend returns error (expected).
- But actually the table has gotten added (due to a backend bug). So if I Cancel at this stage, and refresh tables list, I see the new table (so far so good).
- The problem is when I click on the new table. It spins forever. I checked the GET API and it was able to retrieve the table.

**Comment by shahsank3t** [comment]
@npawar updated the PR with additional fixes and also added Schema Edit & Delete in Schema details page.

**Comment by npawar** [comment]
Thanks @shahsank3t ! Just 2 minor things remaining:

- I still see the issues 6 & 7 from the above list.
- When table config is invalid, can the whole exception be shown? For example, I tried to create OFFLINE table foo, and I set in Indexing & Encoding, the same column as None encoding and Inverted indexing (which is an invalid combination). In the error on UI I only see `“Invalid table config foo_OFFLINE"` but in the log I see the whole message is being returned `"Invalid table config: foo_OFFLINE exception: Cannot create an Inverted index on column aa specified in the noDictionaryColumns config" `. So can the whole message be shown on the UI?

**Comment by shahsank3t** [comment]
@npawar Fixed issues you reported.
I didn't receive the complete error log in API response like you mentioned but the below one:
> {"code":400,"error":"Invalid table config: airlineStats_OFFLINE"}

so for now, showing only the error value.

**Comment by npawar** [comment]
Thanks @shahsank3t ! I will fix the API for the validate.

**Review by npawar — APPROVED** [review]
LGTM! Thanks for working on this, it looks great!

**Pull request merged**
