### PR TITLE
[TE] frontend = aaronucsd/removed error default state

### PR DESCRIPTION
**Pull request by aaronucsd**

### CODE REVIEW

**Comment by apucher** [comment]
I wonder if this is actually the root-cause :-) It seems like the RCA controller should catch error by itself and fix it.

**Comment by aaronucsd** [comment]
@apucher Yeah, my error catch all for any  route that does not handle it itself. So the fix really is why it broke and gracefull add code to handle the error. But you said the `catch-all `return home` link was preventing so i can remove for now. But this is meant to catch any error that bubbled all the why up.

**Comment by aaronucsd** [comment]
I don't have much context yet until i research into it more..Maybe leave the error substate for now?

**Comment by apucher** [comment]
yes. i'd leave this in for now and instead add some "message-and-reset-to-blank" error-handling in the rootcause route

**Comment by npawar** [comment]
Closed this PR due to 6 months inactivity. Reopen if needed.

**Pull request closed without merging**
