### PR TITLE
Extends StreamingSelectionOnlyCombineOperator from BaseCombineOperator

### PR DESCRIPTION
**Pull request by mqliang**
## Description
This PR refactor StreamingSelectionOnlyCombineOperator to make it extends from BaseCombineOperator. Since https://github.com/apache/incubator-pinot/pull/6680 has instrumented BaseCombineOperator query execution code with thread cpu time. With this refactoring, StreamingSelectionOnlyCombineOperator will also get instrumented. 

## Upgrade Notes
Does this PR prevent a zero down-time upgrade? (Assume upgrade order: Controller, Broker, Server, Minion)
* [ ] Yes (Please label as **<code>backward-incompat</code>**, and complete the section below on Release Notes)

Does this PR fix a zero-downtime upgrade introduced earlier?
* [ ] Yes (Please label this as **<code>backward-incompat</code>**, and complete the section below on Release Notes)

Does this PR otherwise need attention when creating release notes? Things to consider:
- New configuration options
- Deprecation of configurations
- Signature changes to public methods/interfaces
- New plugins added or old plugins removed
* [ ] Yes (Please label this PR as **<code>release-notes</code>** and complete the section on Release Notes)
## Release Notes
If you have tagged this as either backward-incompat or release-notes,
you MUST add text here that you would like to see appear in release notes of the
next release.

If you have a series of commits adding or enabling a feature, then
add this section only in final commit that marks the feature completed.
Refer to earlier release notes to see examples of text

## Documentation
If you have introduced a new feature or configuration, please add it to the documentation as well.
See https://docs.pinot.apache.org/developers/developers-and-contributors/update-document

### CODE REVIEW

**Comment by mqliang** [comment]
@siddharthteotia

**Review by Jackie-Jiang — COMMENTED** [review]
Please hold on this change. I'm trying to extract more common logic from the `BaseCombineOperator`, will file the PR soon.
For the streaming operator, we cannot use the same blocking queue because each operator could produce multiple results blocks.

**Comment by Jackie-Jiang** [comment]
@mqliang @siddharthteotia Please take a look at #6696

**Comment by mqliang** [comment]
close this in favor of https://github.com/apache/incubator-pinot/pull/6696

**Pull request closed without merging**
