### PR TITLE
Make dependency on azure-identity provided in pinot-adls plugin

### PR DESCRIPTION
**Pull request by yupeng9**
Due to the license issues of two transitive dependencies from azure-identity, we make `azure-identity` provided scope. Users need to download the jar and put it on the classpath to use the plugin per the added README
- https://github.com/rtyley/spongycastle/blob/spongy-master/LICENSE.html
- https://github.com/xmlpull-xpp3/xmlpull-xpp3#readme

### CODE REVIEW

**Comment by fx19880617** [comment]
@jackjlli @rkanumul 
We are seeing the license issue from transitive dependencies of `azure-identity` brought in from this PR: https://github.com/apache/incubator-pinot/pull/6531

**Review by fx19880617 — APPROVED** [review]
lgtm.  

@jackjlli @rkanumul Please also take a look

**Review by jackjlli — APPROVED** [review]
LGTM. @rkanumul could you please confirm that you're ok with this?

**Comment by rkanumul** [comment]
LGTM. Should be okay doing that.

**Pull request merged**
