### PR TITLE
Add spotless maven plugin to enforce java format.

### PR DESCRIPTION
**Pull request by mqliang**
## Description

ref https://github.com/apache/incubator-pinot/issues/6727

This change add a spotless maven plugin to enforce java format.

If java file is not formatted properly,  all pipelines of `Pinot Tests / Pinot Quickstart on JDK XXX` will failed and hint developer to run `mvn spotless:apply` to fix the violation.

NOTE:
Currently, just add two basic rules:
* Default import order
* Remove unused imports

It's possible to add some more strict rules (via [the goolge-formatter](https://github.com/google/google-java-format) or [the prettier-formatter](https://github.com/prettier/prettier) ). For example, if we add the prettier formatter as follows in the plugin configuration:
```
       <configuration>
          <java>
            <includes>
              <include>src/main/java/**/*.java</include>
              <include>src/test/java/**/*.java</include>
            </includes>
            <importOrder />
            <removeUnusedImports />

            <prettier>
	      <devDependencies>
	          <prettier>2.0.5</prettier>
	          <prettier-plugin-java>0.8.0</prettier-plugin-java>
	      </devDependencies>
	      <config>
	          <tabWidth>2</tabWidth>
	          <parser>java</parser>
	      </config>
	    </prettier>

          </java>
        </configuration>
```
It will use 2 spaces as indention and format all function definition/calling code as using one line for each parameter, e.g.

```
public class HelloWorld {

  public static void main(String[] args) {
    System.out.println("Hello World!");
  }

  @Override
  public String toString() {
    sum(
    1, 
    2, 
    3, 
    4);
    return "Hello World";
  }

  public int sum(
    int argument1,
    int argument2,
    int argument3,
    int argument4,
    int argument5
  ) {
    return argument1 + argument2 + argument3 + argument4 + argument5;
  }
}
```

[the goolge-formatter](https://github.com/google/google-java-format) can not be used in our case, since it will mess up license headers, see https://github.com/google/google-java-format/issues/168

@mcvsubbu @Jackie-Jiang @fx19880617 @siddharthteotia @mayankshriv I think we may need to discuss whether to adopt the code style of "one line for each parameter in function definition/calling code". I will add the prettier formatter configuration if need be.

## Upgrade Notes
Does this PR prevent a zero down-time upgrade? (Assume upgrade order: Controller, Broker, Server, Minion)
* [ ] Yes (Please label as **<code>backward-incompat</code>**, and complete the section below on Release Notes)

Does this PR fix a zero-downtime upgrade introduced earlier?
* [ ] Yes (Please label this as **<code>backward-incompat</code>**, and complete the section below on Release Notes)

Does this PR otherwise need attention when creating release notes? Things to consider:
- New configuration options
- Deprecation of configurations
- Signature changes to public methods/interfaces
- New plugins added or old plugins removed
* [ ] Yes (Please label this PR as **<code>release-notes</code>** and complete the section on Release Notes)

### CODE REVIEW

**Comment by mqliang** [comment]
@mcvsubbu @Jackie-Jiang @fx19880617 @siddharthteotia @mayankshriv 

Update: just found that the maven plugin support eclipse code formatter profile. Add the  corresponding config and eclipse code style xml file in the 3rd commit. The xml file (`config/eclipse-java-formatter.xml`) is copied from the Apache avro project: https://github.com/apache/avro/blob/master/lang/java/eclipse-java-formatter.xml

You may noticed that we already have a `config/codestyle-eclipse.xml` file, but we can not use it directly, if we change the eclipse reformatter config as `<file>${pinot.root}/config/codestyle-eclipse.xml</file>`, `mvn spotless:apply` will failed with exception:
```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.9.0:apply (default-cli) on project pinot-spi: Execution default-cli of goal com.diffplug.spotless:spotless-maven-plugin:2.9.0:apply failed: java.lang.reflect.InvocationTargetException
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)

```
I guess it's because the `${pinot.root}/config/codestyle-eclipse.xml` is too stale (version=12, while version=15 for `config/eclipse-java-formatter.xml` copied from the Apache avro project.

**Comment by mqliang** [comment]
Test failed because LongMsgOffset.java placed license header incorrectly, send a PR https://github.com/apache/incubator-pinot/pull/6783 to address it. Will rebase after https://github.com/apache/incubator-pinot/pull/6783 is merged

**Comment by Jackie-Jiang** [comment]
Nice work!
I would suggest first only add the rules for the import in the first PR.

We need to be very careful on the code style and keep it compatible with the current Pinot style. I believe the current eclipse style is compatible with the intellij style. We probably should update the existing eclipse style to the latest version. The end goal here should be giving the same result as the IDE auto-format.

**Comment by mqliang** [comment]
> We need to be very careful on the code style and keep it compatible with the current Pinot style. I believe the current eclipse style is compatible with the intellij style. We probably should update the existing eclipse style to the latest version. The end goal here should be giving the same result as the IDE auto-format.

The codestyle-intellj.xml file can be deleted now. Intellj support import eclipse code formatter settings since 2014. I have tried 
to import codestyle-eclipse.xml and it works well (maintaining one file is much easier that maintaining two).  But I agree to add basic formatting rules as the first step. I can send separate PR to delete codestyle-intellj.xml and update codestyle-eclipse.xml if need be.

image

**Comment by Jackie-Jiang** [comment]
@mqliang Yes I totally agree maintaining one file is easier and more desired. I'm not sure if eclipse style tracks all the available options in the intellij style. If not, let's try to keep the current style as much as possible because most of the files already follow the format. When enabling the plugin, only the files that do not follow the current style should be changed.

**Review by Jackie-Jiang — COMMENTED** [review]
Can we change the import rule to have static import after the regular import? We should keep the current order

**Comment by mqliang** [comment]
> Can we change the import rule to have static import after the regular import? We should keep the current order

Specified the import order as:  java, javax, org, com, other unspecified, static import.

**Comment by Jackie-Jiang** [comment]
@mqliang 

> Specified the import order as: java, javax, org, com, other unspecified, static import.

I think we are following alphabetical order on regular import, followed by static import

**Comment by mqliang** [comment]
@Jackie-Jiang 
> I think we are following alphabetical order on regular import, followed by static import

Done. Now all imports are split into two section: regular import in alphabetical order, static import

**Review by Jackie-Jiang — APPROVED** [review]
This is great! Well done!

**Pull request merged**
