### PR TITLE
Make PQL use LIMIT N if TOP N is not set

### PR DESCRIPTION
**Pull request by fx19880617**
Make group by query to use `LIMIT N` to set _topN field if `TOP N` is not present.

### CODE REVIEW

**Comment by Jackie-Jiang** [comment]
I think this will break certain LinkedIn use cases where people blindly put LIMIT 0 for group by queries. @mcvsubbu @mayankshriv Do you remember seeing such use cases?

**Comment by kishoreg** [comment]
> I think this will break certain LinkedIn use cases where people blindly put LIMIT 0 for group by queries. @mcvsubbu @mayankshriv Do you remember seeing such use cases?

limit 0 without TOP? if yes, maybe check for recordLimit > 0

**Comment by mcvsubbu** [comment]
Yes, we do have some queries that do this. I am not sure what we said in the spec on open source, but we need to be compat.

**Comment by Jackie-Jiang** [comment]
@kishoreg I think using limit only if it is larger than 0 is the safe option here.

**Pull request merged**
