### PR TITLE
Nightly deploy Pinot to jfrog bintray

### PR DESCRIPTION
**Pull request by jackjlli**
This PR adds the cron job to nightly deploy Pinot to jfrog bintray.

If the build is triggered by cron job, the version of Pinot would be set from 0.3.0-SNAPSHOT to 0.3.0-dev-{buildNumber}, and then deployed to bintray.

### CODE REVIEW

**Comment by snleee** [comment]
@jackjlli  Is this compatible with our existing apache build pipeline?

Can you check if the following would give you the correct jar files? 
```
mvn install -DskipTests -Papache-release,bin-dist

$ cd pinot-distribution/target
$ ls
...
-rw-r--r-- 1 snlee eng 115915316 Mar 21 14:25 apache-pinot-incubating-0.3.0-bin.tar.gz
-rw-r--r-- 1 snlee eng 490 Mar 21 14:25 apache-pinot-incubating-0.3.0-bin.tar.gz.asc
-rw-r--r-- 1 snlee eng 128 Mar 21 14:26 apache-pinot-incubating-0.3.0-bin.tar.gz.sha512
-rw-r--r-- 1 snlee eng 37404419 Mar 21 14:25 apache-pinot-incubating-0.3.0-src.tar.gz
-rw-r--r-- 1 snlee eng 490 Mar 21 14:25 apache-pinot-incubating-0.3.0-src.tar.gz.asc
-rw-r--r-- 1 snlee eng 128 Mar 21 14:26 apache-pinot-incubating-0.3.0-src.tar.gz.sha512
```

**Comment by jackjlli** [comment]
> @jackjlli Is this compatible with our existing apache build pipeline?

Yes, it's compatible with our existing build pipline.

> Can you check if the following would give you the correct jar files?

I cannot with the command you pasted even in master branch though. Here is the exception message:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11.297 s
[INFO] Finished at: 2020-03-24T19:26:58-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.6:sign (sign-release-artifacts) on project pinot: Unable to execute gpg command: Error while executing process. Cannot run program "gpg": error=13, Permission denied -> [Help 1]
```

**Comment by snleee** [comment]
@Jackie-Jiang oh yeah, it needs some set up to run that cmd. Anyway, I think that it's fine as long as it's backward compatible.

**Comment by Jackie-Jiang** [comment]
> @Jackie-Jiang oh yeah, it needs some set up to run that cmd. Anyway, I think that it's fine as long as it's backward compatible. Pls ping me when this is ready for review.

Wrong `at` lol

**Comment by jackjlli** [comment]
I'm closing this PR because of the following statement from Travis doc:
```
Please note that encrypted environment variables are not available for pull requests from forks.
```
I've created a new PR from a branch: https://github.com/apache/incubator-pinot/pull/5181

**Pull request closed without merging**
