### PR TITLE
Allow completing segments to finish before stopping LLC Segment Manager

### PR DESCRIPTION
**Pull request by mcvsubbu**
Added a stop() method to LLC segment manager, so that we can allow the segments
that are completing to be done, and not allow new segments to start their
completion process while controller is shutting down

### CODE REVIEW

**Comment by mcvsubbu** [comment]
Addresses issue #3594

**Comment by mcvsubbu** [comment]
Occurred to me that if we start ValidationManager soon after a leadership gain, we don't need to do this PR?

**Comment by sunithabeeram** [comment]
Looks like @npawar also attempted to fix this in https://github.com/apache/incubator-pinot/pull/3591 :)

> Occurred to me that if we start ValidationManager soon after a leadership gain, we don't need to do this PR?

I guess if the previous leader is not "dead" it could continue running validation-mgr - unless there is a periodic isLeader() check that lets the old controller give up.

**Comment by mcvsubbu** [comment]
> Looks like @npawar also attempted to fix this in #3591 :)
> 
> > Occurred to me that if we start ValidationManager soon after a leadership gain, we don't need to do this PR?
> 
> I guess if the previous leader is not "dead" it could continue running validation-mgr - unless there is a periodic isLeader() check that lets the old controller give up.

Yes, @npawar and I talked about it. We need to make sure that we check the leadership before every new table we process. If we are not leader, stop the validationmanager right away.

**Pull request merged**
