### PR TITLE
Adding CreateSegmentCommandV2 command

### PR DESCRIPTION
**Pull request by fx19880617**
Sample usage: 
```
pinot-admin.sh CreateSegmentV2 \
-dataDir /tmp/pinot/segmentv2/data \
-outDir /tmp/pinot/segmentv2/out \
-schemaFile /tmp/pinot/segmentv2/conn_schema.json \
-tableConfig /tmp/pinot/segmentv2/conn_table_config.json \
-segmentName conn-test \
-overwrite
```

Test table config/schema/data:
[segmentv2.zip](https://github.com/apache/incubator-pinot/files/3618890/segmentv2.zip)

### CODE REVIEW

**Comment by kishoreg** [comment]
Existing command is too complicated and needs segment generation config. I would like to simplify this. Touching existing will break compatibility, so it’s better add a new one and deprecate the existing one.

**Comment by mcvsubbu** [comment]
In that case, let us add a print to the existing one to direct the user to this new command, and mention that it is deprecated. Over time, we can remove the older one. 
I have not looked through fully, but we must add a hook to pick up custom config, and naming schemes.
If one is not doing anything special like I mentioned above, the V2 command should work, right?

**Comment by kishoreg** [comment]
Yes. Which custom config are useful? Can we put them as part of tableConfig. 

I am trying to see if we can move towards 3 main sections to setup a table 

Schema
TableConfig
IngestionConfig Batch/stream

**Comment by fx19880617** [comment]
closed this as we moved to new ingestion spec things

**Pull request closed without merging**
