### PR TITLE
Bump up swagger-ui version and update related code

### PR DESCRIPTION
**Pull request by jackjlli**
## Description
This PR bumps up swagger-ui version and updates related code.

vulnerability: Swagger-ui before 3.18.0 is vulnerable to Reverse Tabnabbing. Setting target="_blank" on anchor tags is unsafe unless used in conjunction with the rel="noopener" attribute. Opening a link via target blank attribute can change the original page, origin policy restrictions set by the browser can be bypassed.

The previous PR (https://github.com/apache/incubator-pinot/pull/5896) didn't make the related required code change in html files, and some frond-end files have already changed their locations in the newer swagger-ui version.

The below is the screenshot after making the code change:
Screen Shot 2020-08-28 at 1 43 21 PM

### CODE REVIEW

**Comment by kishoreg** [comment]
what was the bug in the previous PR?

**Comment by kishoreg** [comment]
> what was the bug in the previous PR?

Never mind looked at the diff and figured it out. Thanks for fixing it.

**Comment by jackjlli** [comment]
@kishoreg yeah it's because the locations for those front-end related files like css, js files have changed in the newer swagger-ui version.

**Comment by mr-agrwal** [comment]
LGTM

**Pull request merged**
