### PR TITLE
UI integration of instance and segment operations

### PR DESCRIPTION
**Pull request by shahsank3t**
## Description
Adding Operations for Instances (Server & Broker)
image
image
image

Adding Operations for Segment 
image
image

### CODE REVIEW

**Comment by mayankshriv** [comment]
1. Seems like I need to do mvn install to see the UI changes (as in, IDE does not build on its own). If there's a way to automate that, it would be nice.
2. Edit Tag does not seem to take the new tag. Edit Config works for editing/adding tags.
3. Drop: Says instance cannot be dropped as it is live.

**Comment by shahsank3t** [comment]
@mayankshriv 
> - Seems like I need to do mvn install to see the UI changes (as in, IDE does not build on its own). If there's a way to automate that, it would be nice.

Will check that out and see what can be done but as part of another PR.

> - Edit Tag does not seem to take the new tag. Edit Config works for editing/adding tags.

We need to press `Enter`, `Space` or `Comma (,)` to create tag pills, and only then that Tag will be saved. Users can add N number of tags and that's the reason the user needs to do an extra step.

> - Drop: Says instance cannot be dropped as it is live.

UI is showing the status sent by the backend on hitting the drop API.

**Comment by npawar** [comment]
> @mayankshriv
> 
> > * Seems like I need to do mvn install to see the UI changes (as in, IDE does not build on its own). If there's a way to automate that, it would be nice.
> 
> Will check that out and see what can be done but as part of another PR.
> 
> > * Edit Tag does not seem to take the new tag. Edit Config works for editing/adding tags.
> 
> We need to press `Enter`, `Space` or `Comma (,)` to create tag pills, and only then that Tag will be saved. Users can add N number of tags and that's the reason the user needs to do an extra step.
> 
> > * Drop: Says instance cannot be dropped as it is live.
> 
> UI is showing the status sent by the backend on hitting the drop API.

Hey @shahsank3t , I’m seeing similar behavior as reported by Mayank for Edit Tags, but only for Server case. Broker works fine for me. Even in Server case, remove tag worked and edit config worked.

@mayankshriv the drop behavior is correct. I verified that the backend is returning the message. Something seems off at the backend side. I remember we used to be able to drop instances after table has been deleted. Will check that out.

**Comment by shahsank3t** [comment]
@npawar @mayankshriv 
made the changes so we no longer need to press "Enter", "Space" or "Comma" to make a chip before saving tags.

**Comment by npawar** [comment]
> @npawar @mayankshriv
> made the changes so we no longer need to press "Enter", "Space" or "Comma" to make a chip before saving tags.

Saw that it worked. Thanks

**Review by npawar — APPROVED** [review]

**Pull request merged**
