### PR TITLE
[TE] move dashboard resources for refactoring

### PR DESCRIPTION
**Pull request by vincentchenjl**
This PR is a followup on the refactoring effort that split thirdeye-dashboard module from the original thirdye-pinot module (#6026). Here are the changes that this PR is going to make.

- Move `thirdeye-pinot/src/main/resources/schema/` to `thirdeye-dashboard` because all the test cases are moved to there.

- Move `thirdeye-pinot/src/main/resources/assets` and `thirdeye-pinot/src/main/resources/scripts` to `thirdeye-dashboard` because these two are only used by the dashboard.

- Remove `thirdeye-pinot/src/main/resources/META-INF/persistence.xml`

- Change frontend compilation output path to `thirdeye-dashboard/src/main/resources/app`

### CODE REVIEW

**Review by harleyjj — APPROVED** [review]
LGTM

**Review by suvodeep-pyne — CHANGES_REQUESTED** [review]
@vincentchenjl 
Moving the `app`, `assets` and `scripts` resources look great! I missed that.

The idea of `thirdeye-dashboard` is to host the UI part of the thirdeye code while the core business logic stays in `thirdeye-pinot` (to be later called `thirdeye-core`). However, the schema changes shouldn't move to the dashboard server IMO. The doc outlines a separate persistence layer and that could ideally host the sql scripts.

Also, I envision the new coordinator module to be able to access the sql scripts without depending on `thirdeye-dashboard`.

The tests were moved because they behave more like integration tests rather than unit tests. We could have a separate module like `thirdeye-integration-tests` for them if that makes sense.

**Comment by vincentchenjl** [comment]
> Also, I envision the new coordinator module to be able to access the sql scripts without depending on `thirdeye-dashboard`.
I agree on this point. However, having all the tests in `thideye-dashboard` and `create-schema.sql` in `thirdeye-pinot` cause `mvn install` to fail. There are two ways going forward I can think of right now. One is to move `create-schema.sql` to `thirdeye-dashboard`, and the other is to move the test cases that require those schema back to `thirdeye-pinot`. Also, the last PR already moved `persistence-local.yml` to `thirdeye-dashboard`, so we also need to move it back if we want to go for second approach. Please let me know if there is any other way to do it. 
`[ERROR] beforeMethod(org.apache.pinot.thirdeye.detection.alert.filter.ToAllRecipientsDetectionAlertFilterTest)  Time elapsed: 0.003 s  <<< FAILURE!
java.lang.RuntimeException: java.io.FileNotFoundException: file:/Users/jianchen/dev-projects/incubator-pinot/thirdeye/thirdeye-pinot/target/thirdeye-pinot-1.0.0-SNAPSHOT.jar!/schema/create-schema.sql (No such file or directory)
        at org.apache.pinot.thirdeye.detection.alert.filter.ToAllRecipientsDetectionAlertFilterTest.beforeMethod(ToAllRecipientsDetectionAlertFilterTest.java:77)`

**Comment by suvodeep-pyne** [comment]
@vincentchenjl 
`persistence-local.yml` is a test resource I believe. I think we need to have a way of reading the sql file from a different module. This seems like a mvn + macOS issue since the tests run fine on the IDE and on GitHub/Travis.

Moving back the SQL tests is definitely something that we could do but the problem is that there are tests which aren't that modular. There may be some work here.

Feel free to move the UI app and assets to the `dashboard` module since they seem unrelated to the SQL bug. We can tackle this issue separately.

**Comment by vincentchenjl** [comment]
@suvodeep-pyne I test `mvn install` in Linux and same issue still persists. I think we should resolve this ASAP. Even though it is not a blocking issue, it causes issues when people set up thirdeye.

**Comment by vincentchenjl** [comment]
> @vincentchenjl
> Shared a fix on slack on Friday. Please take a look.
> 
> I'm curious how Travis is running fine?

**Review by suvodeep-pyne — APPROVED** [review]
LGTM. This looks great! Thanks a lot @vincentchenjl !

**Review by jihaozh — APPROVED** [review]

**Pull request merged**
