### PR TITLE
Upgrade t-digest to latest release

### PR DESCRIPTION
**Pull request by tdunning**
## Upgrade Notes
Does this PR prevent a zero down-time upgrade? (Assume upgrade order: Controller, Broker, Server, Minion)
* [ ] Yes (Please label as **<code>backward-incompat</code>**, and complete the section below on Release Notes)

Does this PR fix a zero-downtime upgrade introduced earlier?
* [ ] Yes (Please label this as **<code>backward-incompat</code>**, and complete the section below on Release Notes)

Does this PR otherwise need attention when creating release notes? Things to consider:
- New configuration options
- Deprecation of configurations
- Signature changes to public methods/interfaces
- New plugins added or old plugins removed
* [ ] Yes (Please label this PR as **<code>release-notes</code>** and complete the section on Release Notes)

### CODE REVIEW

**Comment by mayankshriv** [comment]
Restarted tests.

**Comment by mayankshriv** [comment]
A link to release notes on TDigest side would be handy to include in the PR description.

**Comment by mayankshriv** [comment]
Hmm, seems like a real build failure: ```Failed to execute goal on project pinot-segment-local: Could not resolve dependencies for project org.apache.pinot:pinot-segment-local:jar:0.8.0-SNAPSHOT: Failed to collect dependencies at com.tdunning:t-digest:jar:3.3: Failed to read artifact descriptor for com.tdunning:t-digest:jar:3.3: Could not find artifact com.tdunning:t-digest-parent:pom:3.3 in central (https://repo.maven.apache.org/maven2)```

**Comment by tdunning** [comment]
Good suggestion.

This blog is the high-level view, I will collect a more formal release note.

**Comment by tdunning** [comment]
This is very odd. If I look in
https://repo.maven.apache.org/maven2/com/tdunning/t-digest/3.3
I see the artifacts.

Is there a cache messing you about?

**Comment by tdunning** [comment]
I meant this blog.

https://tdunning.blogspot.com/2021/06/whats-new-in-t-digest-new-version-32.html

**Comment by tdunning** [comment]
OK. I understand this now.

The problem is that I did an incompetent job of breaking t-digest into
multiple modules. This meant that I needed to publish the parent pom as an
artifact.

I will have to recut the release. Should get that out in a day or two.

**Comment by mayankshriv** [comment]
> OK. I understand this now. The problem is that I did an incompetent job of breaking t-digest into multiple modules. This meant that I needed to publish the parent pom as an artifact. I will have to recut the release. Should get that out in a day or two.

Thanks @tdunning, much appreciated.

**Comment by tdunning** [comment]
OK. The artifacts on maven central are now complete and correct.

The demo program at `https://github.com/tdunning/t-digest-example` builds on a clean machine which should mean that Pinot itself should build cleanly.

How can we relaunch the integration tests?

**Comment by mayankshriv** [comment]
Ted, I have re-launched the tests. Typically an update of your branch will relaunch it as well.

**Comment by mayankshriv** [comment]
@tdunning, I have relaunched the tests. Typically an update in your branch will relaunch them.

**Comment by tdunning** [comment]
Cool.

The change here is a new artifact in maven central so your manual restart
was just the thing.

**Review by mayankshriv — APPROVED** [review]

**Pull request merged**
