### PR TITLE
Fix Travis build timeout

### PR DESCRIPTION
**Pull request by jackjlli**
We've seen some travis build failed because of 50 mins timeout. It may be due to the increased number of tests in the repo.
This PR fixes Travis build timeout.

### CODE REVIEW

**Comment by Jackie-Jiang** [comment]
This is incorrect. That one only starts a background task to avoid failing the task without output for 10 minutes. I think the 50 minutes is a hard limit

**Comment by jackjlli** [comment]
> This is incorrect. That one only starts a background task to avoid failing the task without output for 10 minutes. I think the 50 minutes is a hard limit

Yeah, also saw the build failed. It seems we'd need to split the test into multiple parts.

**Comment by jackjlli** [comment]
Checked the log. It only took 33 mins for Unit Test job to finish:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 33:51 min
[INFO] Finished at: 2020-04-07T20:38:42Z
[INFO] Final Memory: 132M/810M
[INFO] ------------------------------------------------------------------------
```
It took 25 mins for the Integration Test job to finish:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 25:02 min
[INFO] Finished at: 2020-04-07T20:34:26Z
[INFO] Final Memory: 136M/1006M
[INFO] ------------------------------------------------------------------------
```
It seems most of the time it's preparing/storing for the cache.

**Comment by Jackie-Jiang** [comment]
> > This is incorrect. That one only starts a background task to avoid failing the task without output for 10 minutes. I think the 50 minutes is a hard limit
> 
> Yeah, also saw the build failed. It seems we'd need to split the test into multiple parts.

@jackjlli I don't see any test runs longer than 50 minutes unless something is wrong. Which test did you find that timed out?

**Comment by jackjlli** [comment]
> > > This is incorrect. That one only starts a background task to avoid failing the task without output for 10 minutes. I think the 50 minutes is a hard limit
> > 
> > 
> > Yeah, also saw the build failed. It seems we'd need to split the test into multiple parts.
> 
> @jackjlli I don't see any test runs longer than 50 minutes unless something is wrong. Which test did you find that timed out?

As I mentioned in the comment above, the unit test job and integration test job finished around 30 mins. And it took rest of the time on preparing/storing build cache.

**Comment by Jackie-Jiang** [comment]
I don't quite understand what are you trying to fix here. The reason why the tests failed under this pr is because the background travis_wait is not terminated and holds the test from finishing. Nothing related to storing the cache.

**Comment by jackjlli** [comment]
@Jackie-Jiang What I try to solve here is that travis build failed because of 50 mins timeout. I'm trying to figure out a way to make it pass. Obviously it took only 30 mins for mvn command to finish. The rest of the time spent is for preparing/storing build cache.
In the latest push, I've tried the workaround mentioned in this https://github.com/travis-ci/travis-ci/issues/6410. Let's see how it goes.

**Comment by Jackie-Jiang** [comment]
@jackjlli I'm able to find some travis failure on this, e.g. https://travis-ci.org/github/apache/incubator-pinot/builds/671333682
From what I saw, since we merged #5190 the travis test has taken significant longer. You might want to check what is changed in that pr. Are we uploading much bigger cache data?

**Comment by Jackie-Jiang** [comment]
For this job: https://travis-ci.org/github/apache/incubator-pinot/jobs/672310378
Setting up build cache before tests (line 443 - 452) took nearly 12 minutes
Storing build cache after tests (line 10284 - 10298) took nearly 10 minutes

We need to figure out why it took this long, and whether we are caching something unnecessary

**Pull request closed without merging**
