### PR TITLE
add auth support to generator.sh

### PR DESCRIPTION
**Pull request by apucher**
## Description
add auth support to generator.sh

## Upgrade Notes
Does this PR prevent a zero down-time upgrade? (Assume upgrade order: Controller, Broker, Server, Minion)
* [ ] Yes (Please label as **<code>backward-incompat</code>**, and complete the section below on Release Notes)

Does this PR fix a zero-downtime upgrade introduced earlier?
* [ ] Yes (Please label this as **<code>backward-incompat</code>**, and complete the section below on Release Notes)

Does this PR otherwise need attention when creating release notes?=
* [ ] Yes (Please label this PR as **<code>release-notes</code>** and complete the section on Release Notes)

## Release Notes
None

## Documentation
None

### CODE REVIEW

**Review by xiangfu0 — APPROVED** [review]

**Comment by xiangfu0** [comment]
Shall we also think of supporting auth for launch ingestion job ?

**Comment by apucher** [comment]
ingestion jobs already support auth: (a) via YAML configs, and (b) via command-line properties

**Comment by xiangfu0** [comment]
> ingestion jobs already support auth: (a) via YAML configs, and (b) via command-line properties

cool, then we just need an example for that.

**Comment by apucher** [comment]
already there (see bottom): https://docs.pinot.apache.org/operators/tutorials/authentication-authorization-and-acls

**Pull request merged**
