### PR TITLE
DataGenerator should tolerate DATE_TIME and COMPLEX fields

### PR DESCRIPTION
**Pull request by apucher**
## Description
Fixes a forward compatibility issue with DATE_TIME fields in the data generator

## Upgrade Notes
Does this PR prevent a zero down-time upgrade?
**no**

Does this PR fix a zero-downtime upgrade introduced earlier?
**no**

Does this PR otherwise need attention when creating release notes? Things to consider:
**no**

### CODE REVIEW

**Comment by Jackie-Jiang** [comment]
@npawar Please take a look and see whether we should support generating data for date time fields

**Comment by npawar** [comment]
it should be fine to ignore the field for now. Eventually we want to handle it just like TIME case

**Comment by apucher** [comment]
@Jackie-Jiang we already do when using the pattern data generator. the crappy old code is around for backwards compatibility only.

**Comment by apucher** [comment]
we may actually consider removing it. afaik there's no active use of it

**Pull request merged**
