### PR TITLE
Make required interfaces or classes serializable for spark

### PR DESCRIPTION
**Pull request by jackjlli**
## Description
This PR makes the required changes, so that interfaces/classes can be used directly in spark. 
The reason why Serializable is needed is that objects need to be passed from driver to executors, which requires serialization on those objects.

## Upgrade Notes
Does this PR prevent a zero down-time upgrade? (Assume upgrade order: Controller, Broker, Server, Minion)
* [ ] Yes (Please label as **<code>backward-incompat</code>**, and complete the section below on Release Notes)

Does this PR fix a zero-downtime upgrade introduced earlier?
* [ ] Yes (Please label this as **<code>backward-incompat</code>**, and complete the section below on Release Notes)

Does this PR otherwise need attention when creating release notes? Things to consider:
- New configuration options
- Deprecation of configurations
- Signature changes to public methods/interfaces
- New plugins added or old plugins removed
* [ ] Yes (Please label this PR as **<code>release-notes</code>** and complete the section on Release Notes)
## Release Notes
If you have tagged this as either backward-incompat or release-notes,
you MUST add text here that you would like to see appear in release notes of the
next release.

If you have a series of commits adding or enabling a feature, then
add this section only in final commit that marks the feature completed.
Refer to earlier release notes to see examples of text

## Documentation
If you have introduced a new feature or configuration, please add it to the documentation as well.
See https://docs.pinot.apache.org/developers/developers-and-contributors/update-document

### CODE REVIEW

**Comment by fx19880617** [comment]
Thanks for making the changes!

Is it possible to add a test to check if the given classes are Spark serializable? So we can ensure further changes won't break this.

**Comment by jackjlli** [comment]
> Thanks for making the changes!
> 
> Is it possible to add a test to check if the given classes are Spark serializable? So we can ensure further changes won't break this.

That's a good idea! I've added a unit test in pinot-spark module to test that.

**Review by fx19880617 — APPROVED** [review]
lgtm

**Comment by fx19880617** [comment]
> lgtm, not sure if v0_deprecatd is a good place to put this test, but we can always move it if needed.

Maybe move it into `pinot-connectors/pinot-spark-connector`?

**Comment by jackjlli** [comment]
> > lgtm, not sure if v0_deprecatd is a good place to put this test, but we can always move it if needed.
> 
> Maybe move it into `pinot-connectors/pinot-spark-connector`?

Yeah I've thought about it in the first place. While pinot-spark-connector is written in scala, plus the spark version (2.12) on that isn't the same as the one in pinot-spark module (2.11), which means that there is no tests back for spark 2.11.  
So I'll just leave it here for now. We can always move it if necessary in the future.

**Pull request merged**
