### PR TITLE
Supporting adding of tables & schema from UI and added Timeout in Query Console

### PR DESCRIPTION
**Pull request by shahsank3t**
## Description
**Add Schema & Table**
1. Adding Schema:
image

2. Adding Table  (Table Config is editable): 
image

**Add Table Only*
image

Note:  Table Name entered for the new table in `Add Table Only` should match with the existing schema name.

### CODE REVIEW

**Comment by shahsank3t** [comment]
Added Timeout in Query Console
image

**Comment by npawar** [comment]
@shahsank3t Some issues I found:
1. The replication should also get set into the "replicasPerPartition"
2. The schemaName should also get set into the segmentsConfig -> schemaName
3. I also noticed the spinning circle that Jack mentions.

**Comment by npawar** [comment]
> @shahsank3t Thanks for working on it. I've tested this PR locally and found out the following thing:
> 
> * the UI cannot route to the correct page after clicking "save" button for "Add Table" for the first time. There is a circle that keeps spinning.
> * when clicking into "Add Table", after typing the table name, the UI will prompt "schema not found" on the top right side of the UI.

Regarding your second point, for Add Table only operation, we're expecting that user already has schema with same name as the table. We have already deprecated the schemaName in the table config and have comments in place to indicate that schema name should be equal to the table name.

**Comment by npawar** [comment]
Another change:
For adding column of DATETIME type, the fields should be TimeUnit  (for MILLIS, SECONDS dropdown) and TimeFormat (for EPOCH, SDF dropdown), instead of TimeSize and TimeUnit.

And could we have Granularity interval before Granularity Unit?

**Comment by shahsank3t** [comment]
@npawar we show another format field when we select SDF from TimeFormat. What should we call that?

**Comment by npawar** [comment]
> @npawar we show another format field when we select SDF from TimeFormat. What should we call that?

Lets call that Time Pattern

**Comment by shahsank3t** [comment]
@jackjlli @npawar 
Thanks for taking the time to try out the changes.
I have updated the PR with the reported issues and concerns.

**Comment by npawar** [comment]
Found another corner case - 
I Clicked on Add Table & Schema. 
I added 2 columns in the schema with the same name. 
Selected OFFLINE table and provided a name.
Clicked Save.

The POST schema call must've failed in the backend. As a result, no schema was created. But the table was still created. 
I tried that schema on Swagger POST and verified that it should fail. Here's the reference schema:
```
{
  "schemaName": "",
  "dimensionFieldSpecs": [
    {
      "name": "aa",
      "dataType": "INT"
    },
    {
      "name": "aa",
      "dataType": "LONG"
    }
  ],
  "metricFieldSpecs": [],
  "dateTimeFieldSpecs": []
}
```

**Comment by npawar** [comment]
One more:
1. Clicked on Add Schema and Table
2. Added STRING dimension "x"
3. Added STRING datetime "y"
4. Entered tableName "foo" and selected "OFFLINE". At this stage, "y" is shown in the dropdown for time.
5. Now went to the top section and added another LONG datetime "z"
6. Went to the bottom section to change time column to "z", but don't see it in the dropdown. (Manually edited json from y to z and that worked)

**Comment by npawar** [comment]
Third one:
Clicked on Add Table.
Enter a tableName "foo", such that no schema with that name exists.
The schemaName in the tableConfig is automatically filled out as "foo" - which is the correct behavior. But that schema doesn't exist, so I manually change this to some other schemaName, say "bar".
Click Save.

Now when I go look at the tableConfig "foo", I was expecting schemaName "bar", but it got saved as "foo".

**Comment by shahsank3t** [comment]
Thanks for the detailed steps  @npawar 
I have fixed all the bugs and updated the PR.

**Comment by npawar** [comment]
Thanks @shahsank3t ! Looks good to me

**Review by npawar — APPROVED** [review]

**Comment by jackjlli** [comment]
Tested it locally and everything looks good. Thanks @shahsank3t !

**Pull request merged**
