### PR TITLE
Rename stream plugin pkgs

### PR DESCRIPTION
**Pull request by mcvsubbu**
Moved stream plugin packages to new package names

As per https://docs.google.com/document/d/1160Wz-694-SDuFEKrZ2rW_iIswcTqk4hJ3k-BNp0BaI/edit#

### CODE REVIEW

**Comment by fx19880617** [comment]
Will this package name change causing existing realtime tables fail to start consuming?
I've also updated the quickstart and examples in https://github.com/apache/incubator-pinot/pull/4956

**Comment by mcvsubbu** [comment]
> Will this package name change causing existing realtime tables fail to start consuming?
> I've also updated the quickstart and examples in #4956

Not sure why you ask, but yes, one may need to change config files to point to the right class, or load the right class names. I will look through other files to see if there are places where we hard-code classpath names

**Comment by fx19880617** [comment]
> > Will this package name change causing existing realtime tables fail to start consuming?
> > I've also updated the quickstart and examples in #4956
> 
> Not sure why you ask, but yes, one may need to change config files to point to the right class, or load the right class names. I will look through other files to see if there are places where we hard-code classpath names

What I mean is that if users upgrade to current master, then all their existing tables will stop consuming after the upgrade as we specify the stream factory class in table config, which is changed after this.

**Comment by mcvsubbu** [comment]
> > > Will this package name change causing existing realtime tables fail to start consuming?
> > > I've also updated the quickstart and examples in #4956
> > 
> > 
> > Not sure why you ask, but yes, one may need to change config files to point to the right class, or load the right class names. I will look through other files to see if there are places where we hard-code classpath names
> 
> What I mean is that if users upgrade to current master, then all their existing tables will stop consuming after the upgrade as we specify the stream factory class in table config, which is changed after this.

That is true, and must be noted in the release notes.

**Comment by kishoreg** [comment]
Along with mentioning it in the release notes, can we add a hashmap that maps old class to the new class in PluginManager to make this seamless?

**Pull request merged**
