### PR TITLE
Upgrade fastutil to 8.2.3

### PR DESCRIPTION
**Pull request by xueyumusic**
Current fastutil is 6.5.16 and the latest fastutil version is 8.2.3. There are many bugfixes and optimization [between these version](http://fastutil.di.unimi.it/CHANGES). This PR upgrades fastutil to 8.2.3.

### CODE REVIEW

**Comment by kishoreg** [comment]
Are there any backwards incompatible changes? Is it possible to test this with server running old version of fast util and broker new version of fastutil

**Comment by mayankshriv** [comment]
Could you please categorize the code changes into the following buckets:
1. Required for compiling with new library.
2. Required for functional correctness (eg compiles with new library, but fails without this change).
3. Code cleanup not required for library upgrade (I see several changes to replace anonymous classes with lambda).

**Comment by xueyumusic** [comment]
Hi, @kishoreg , I tested [using the experiment in the doc](https://pinot.readthedocs.io/en/latest/getting_started.html#experimenting-with-pinot) with server running old version and controller/broker running new version, it looks the test could pass.

**Comment by xueyumusic** [comment]
Hi, @mayankshriv , the required for compiling with new library is fastutil version in pom.xml.
The rest are all code clean related and not required for library upgrade except one execution statistic test result updated. 
Thanks.

**Comment by mayankshriv** [comment]
@xueyumusic Thanks for clarifying. For future, best to have separate PR's for unrelated changes. Or if the changes are small (and unrelated to the PR's title), explicitly call them out in the description.

@kishoreg Are you ok with this change?

**Comment by mayankshriv** [comment]
@xueyumusic Also, I was curious as to what triggered this change? Did you run into an issue and identified that it was fixed in the newer version, or this is more of a proactive change? If former, please list the issues you ran into in Pinot that will be resolved with this version upgrade.

**Comment by xueyumusic** [comment]
Hi, when investigating select distinct query implementation I found that fastuitl version is a bit old, so submit this pr, thanks~

**Comment by xueyumusic** [comment]
Hi, @mayankshriv when investigating select distinct query implementation I found that fastuitl version is a bit old, so submit this pr, thanks~

**Comment by kishoreg** [comment]
LGTM

**Pull request merged**
