### PR TITLE
Replace Hashmap to Object2IntOpenHashMap in OnHeapStringDictionary

### PR DESCRIPTION
**Pull request by jackjlli**
This PR replaces `Hashmap` to `Object2IntOpenHashMap` in OnHeapStringDictionary. 

https://issues.apache.org/jira/browse/PINOT-8

### CODE REVIEW

**Comment by Jackie-Jiang** [comment]
Can you please benchmark this map vs. HashMap? If I remember correctly, we benchmarked it and it is actually performing worse than the HashMap

**Comment by jackjlli** [comment]
Here are the results by using offheap dictionary, onheap dictionary with HashMap, and onheap dictionary with Object2IntOpenHashMap:
offheap:
```
Total time: 12389
Total time for 10000000 lookups: 15996ms
DictSize,TimeTaken(ms),SegmentSize,NumLookups,Min,Max,Mean,StdDev,Median,Skewness,Kurtosis,Variance,BufferSize
1000000,15996,514501118,10000000,1000.0,1000.0,1000.0,0.0,1000.0,NaN,NaN,0.0
Process finished with exit code 0
```
onheap with HashMap:
```
Total time: 12250
Total time for 10000000 lookups: 237ms
DictSize,TimeTaken(ms),SegmentSize,NumLookups,Min,Max,Mean,StdDev,Median,Skewness,Kurtosis,Variance,BufferSize
1000000,237,514501118,10000000,1000.0,1000.0,1000.0,0.0,1000.0,NaN,NaN,0.0
Process finished with exit code 0
```
onheap with Object2IntOpenHashMap:
```
Total time: 12187
Total time for 10000000 lookups: 242ms
DictSize,TimeTaken(ms),SegmentSize,NumLookups,Min,Max,Mean,StdDev,Median,Skewness,Kurtosis,Variance,BufferSize
1000000,242,514501118,10000000,1000.0,1000.0,1000.0,0.0,1000.0,NaN,NaN,0.0
Process finished with exit code 0
```
As the results shows, there's no big difference on dictionary lookup between using these two hash maps.

**Comment by Jackie-Jiang** [comment]
@jackjlli Can you also benchmark the memory cost for these 2 maps? You can include the benchmark class in the pr.

**Comment by jackjlli** [comment]
I've updated the test and here are the results comparing `Object2IntOpenHashMap` with `HashMap`.

`Object2IntOpenHashMap`:
```
Total time for building segment: 22239
Total time for 10000000 lookups: 1876ms
Memory usage: 2168980704
DictSize,TimeTaken(ms),SegmentSize,NumLookups,Min,Max,Mean,StdDev,Median,Skewness,Kurtosis,Variance,BufferSize
2000000,1876,1029251120,10000000,1000.0,1000.0,1000.0,0.0,1000.0,NaN,NaN,0.0
```
```
Total time for building segment: 22667
Total time for 10000000 lookups: 1901ms
Memory usage: 2168993176
DictSize,TimeTaken(ms),SegmentSize,NumLookups,Min,Max,Mean,StdDev,Median,Skewness,Kurtosis,Variance,BufferSize
2000000,1901,1029251120,10000000,1000.0,1000.0,1000.0,0.0,1000.0,NaN,NaN,0.0
```
```
Total time for building segment: 22174
Total time for 10000000 lookups: 1880ms
Memory usage: 2168980824
DictSize,TimeTaken(ms),SegmentSize,NumLookups,Min,Max,Mean,StdDev,Median,Skewness,Kurtosis,Variance,BufferSize
2000000,1880,1029251120,10000000,1000.0,1000.0,1000.0,0.0,1000.0,NaN,NaN,0.0
```

`HashMap`:
```
Total time for building segment: 22343
Total time for 10000000 lookups: 2294ms
Memory usage: 2248214504
DictSize,TimeTaken(ms),SegmentSize,NumLookups,Min,Max,Mean,StdDev,Median,Skewness,Kurtosis,Variance,BufferSize
2000000,2294,1029251120,10000000,1000.0,1000.0,1000.0,0.0,1000.0,NaN,NaN,0.0
```
```
Total time for building segment: 24396
Total time for 10000000 lookups: 2244ms
Memory usage: 2248201544
DictSize,TimeTaken(ms),SegmentSize,NumLookups,Min,Max,Mean,StdDev,Median,Skewness,Kurtosis,Variance,BufferSize
2000000,2244,1029251120,10000000,1000.0,1000.0,1000.0,0.0,1000.0,NaN,NaN,0.0
```
```
Total time for building segment: 23854
Total time for 10000000 lookups: 2216ms
Memory usage: 2248211648
DictSize,TimeTaken(ms),SegmentSize,NumLookups,Min,Max,Mean,StdDev,Median,Skewness,Kurtosis,Variance,BufferSize
2000000,2216,1029251120,10000000,1000.0,1000.0,1000.0,0.0,1000.0,NaN,NaN,0.0
```
As shown above, `Object2IntOpenHashMap` uses less memory and it takes less time on lookups.

**Pull request merged**
