### PR TITLE
Remove thirdeye

### PR DESCRIPTION
**Pull request by fx19880617**
## Description
Per #6603, we are removing thirdeye from the Pinot repo and relocate it to https://github.com/project-thirdeye/thirdeye
- Remove thirdeye
- Update Github Action

## Release Notes
Remove thirdeye project from Apache Pinot

### CODE REVIEW

**Review by vincentchenjl — APPROVED** [review]
LGTM!

**Review by jihaozh — APPROVED** [review]
LGTM

**Review by jackjlli — APPROVED** [review]
LGTM

**Comment by fx19880617** [comment]
Many thanks guys!

**Pull request merged**
